### ISSUE TITLE
Pagination scaffolding HTML and CSS styling

### ISSUE THREAD

**Issue by dragontheory** [dragontheory/D7460N-APP-with-resizer#14]
The structure of what we will by hiding/showing via total number of visible rows divided into total number of search results. 

Dependent on #15

**Comment by dragontheory** [comment]
Added HTML and CSS styling. 

HTML:

```html
<list-item>
  <list-cell><a href="#">01</a></list-cell>
  <list-cell><a href="#">02</a></list-cell>
  <list-cell><a href="#">03</a></list-cell>
  <list-cell><a href="#">04</a></list-cell>
  <list-cell><a href="#">05</a></list-cell>
</list-item>
```
CSS:
```css
/*-----------------------------
  PAGINATION
-----------------------------*/
app-panel:nth-of-type(3)  panel-header {
  grid-template-columns: 1fr 1fr;
}

app-panel:nth-of-type(3)  panel-header list-item {
  grid-template-columns: repeat(auto-fiT, minmax(3rem, auto));
  grid-template-rows: 1fr;
  box-shadow: 0 1px 0 0 rgb(255,255,255,0.0);
  background-color: rgba(48,190,255,0.0);
  justify-content: end;
}

app-panel:nth-of-type(3)  panel-header list-item list-cell {
  box-shadow: 2px 0 0 -1px rgb(255,255,255,0.2);
  transition: color 250ms, background-color 250ms;
  text-align: center;
}

app-panel:nth-of-type(3)  panel-header list-item list-cell:hover {
  box-shadow: 2px 0 0px -1px rgb(255,255,255,0.2);
  background-color: rgba(48,190,255,0.2);
  color: rgba(255,255,255,1.0);
}
```
